name: Basic CI

on:
  push:
    branches: [main, setup-task]
  pull_request:
    branches: [main, setup-task]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Show Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt
